version: '3.8'

services:
  frontend:
    container_name: db_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  server:
    container_name: db_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    volumes:
      - "./backend/data/mysql/migrations:/app/data/mysql/migrations"
    depends_on:
      - db

  db:
    container_name: db_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  app-network:

volumes:
  db-data: